version: '3.5'

services:
  salsify:
    networks:
      - salsify_network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200

networks:
  salsify_network:
    external: false